const router = require('express').Router()
const controller = require('../Controller/controller')
const controllProduct=require('../Controller/product')

router.get('/register', controller.registerPage)
router.get('/', controller.loginPage)
router.get('/logout', controller.deletepage)
router.get('/index',controllProduct.indexPage)
router.get('/cart',controllProduct.cart)
router.post('/register', controller.userRegister)
router.post('/', controller.login)
router.post('/add_to_cart',controllProduct.addtoCart)
router.post('/remove_products',controllProduct.rmvProducts)
router.post('/edit_product_quantity',controllProduct.editProductQuantity)
module.exports = router;